### ISSUE TITLE
请问子项目 sub-app-js、sub-app-ts 能单独进行运行调试吗

### ISSUE THREAD

**Issue by daijinming** [micro-frontends-vue/preload-routes#1]
请问子项目 sub-app-js、sub-app-ts 能单独进行运行调试吗

**Comment by zh-rocco** [comment]
不可以的。
1. 缺少独立运行的依赖，子项目中不包含 index.html 和 vue 全家桶
2. 独立运行的话，多个项目共享登录态比较麻烦，需要引入 Nginx

**Comment by zh-rocco** [comment]
> 请问子项目 sub-app-js、sub-app-ts 能单独进行运行调试吗

不可以的。

缺少独立运行的依赖，子项目中不包含 index.html 和 vue 全家桶
独立运行的话，多个项目共享登录态比较麻烦，需要引入 Nginx

**Comment by zhangjingge** [comment]
@zh-rocco 想问一下app-enter,app-js,app-ts可以独立打包部署上线吗？

**Comment by zh-rocco** [comment]
> @zh-rocco 想问一下app-enter,app-js,app-ts可以独立打包部署上线吗？

可以的！

只需将 app-js 和 app-ts 的构建结果部署到服务器上，然后在 app-entry 的 html 里引用 app-js 和 app-ts 的入口 js 就可以了

**Comment by zivenday** [comment]
> > 请问子项目 sub-app-js、sub-app-ts 能单独进行运行调试吗
> 
> 不可以的。
> 
> 1. 子项目缺少独立运行的依赖（项目中不包含 index.html 和 vue 全家桶）
> 2. 独立运行的话，多个项目共享登录态比较麻烦，需要引入 Nginx
> 3. 项目间共享组件/方法也比较繁琐

既然没有独立运行，为啥要proxy过去？有点不懂

**Comment by zh-rocco** [comment]
@zivenday 

1. 开发阶段，主项目和每个子项目都运行在独立的 webpack-dev-server 下，所以需要在主项目里 proxy 子项目的入口文件。

2.
> > 请问子项目 sub-app-js、sub-app-ts 能单独进行运行调试吗
> 
> 不可以的。
> 
> 1. 子项目缺少独立运行的依赖（项目中不包含 index.html 和 vue 全家桶）
> 2. 独立运行的话，多个项目共享登录态比较麻烦，需要引入 Nginx
> 3. 项目间共享组件/方法也比较繁琐

这个问题我理解为：能否单独运行子项目进行开发调试。

因为子项目是运行在主项目里的，所以必须同时启动主项目才可以开发调试。

**Comment by yangangzhang** [comment]
您好，那么子项目中的接口如何设置跨域代理呢？
